name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^5.6.0
  firebase_core: ^3.14.0
  google_fonts: ^6.2.1
  provider: ^6.1.2
  dio: ^5.8.0+1
  flutter_spinkit: ^5.2.1
  convert: ^3.1.2
  fluttertoast: ^8.2.12 
  shared_preferences: ^2.5.2
  firebase_messaging: ^15.0.1
  qr_flutter: ^4.1.0
  flutter_local_notifications: ^17.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
